#!/usr/bin/env bash

set -euo pipefail

rm -rf \
	.lighthouseci \
	.netlify \
	.svelte-kit \
	build \
	node_modules \
	static/js/topbar.min.js \
	storybook-static

find . -type f -name 'fixture.json' -delete
