name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      # https://pnpm.io/continuous-integration#github-actions
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run validate script
        run: pnpm validate
